// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelFetch():Promise<void>;

export function FetchDocuments(arg1:main.FetchParams):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SelectExcelFile():Promise<string>;
