// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFetch() {
  return window['go']['main']['App']['CancelFetch']();
}

export function FetchDocuments(arg1) {
  return window['go']['main']['App']['FetchDocuments'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}
